--- 
abstract: Pure Perl implementation of 'HikiDoc' which is a text-to-HTML conversion tool.
author: KAWABATA, Kazumichi (Higemaru) <kawabata@cpan.org>
build_requires: 
  Test::Base: 0
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Text-HikiDoc
no_index: 
  directory: 
    - inc
    - t
requires: 
  File::Basename: 0
  perl: 5.6.0
version: 1.019
